<template><div><h1 id="第三方拓展类" tabindex="-1"><a class="header-anchor" href="#第三方拓展类"><span>第三方拓展类</span></a></h1>
<h2 id="广告类" tabindex="-1"><a class="header-anchor" href="#广告类"><span>广告类</span></a></h2>
<p>脚本位置：source/class/adv/adv_name.php<br>
语言包位置：source/language/adv/lang_name.php</p>
<h6 id="【discuz-x3-0-新增】" tabindex="-1"><a class="header-anchor" href="#【discuz-x3-0-新增】"><span>【Discuz! X3.0 新增】</span></a></h6>
<p>脚本位置：source/plugin/插件目录/adv/adv_name.php<br>
缩略图：source/plugin/插件目录/adv/adv_name.gif</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token php language-php"><span class="token delimiter important">&lt;?php</span>
<span class="token keyword">class</span> <span class="token class-name-definition class-name">adv_name</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> <span class="token variable">$version</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'1.0'</span><span class="token punctuation">;</span><span class="token comment">//脚本版本号</span>
    <span class="token keyword">var</span> <span class="token variable">$name</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'name'</span><span class="token punctuation">;</span><span class="token comment">//广告类型名称 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$description</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'desc'</span><span class="token punctuation">;</span><span class="token comment">//广告类型说明 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$copyright</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'Comsenz Inc.'</span><span class="token punctuation">;</span><span class="token comment">//版权 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$targets</span> <span class="token operator">=</span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'portal'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'home'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'member'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'forum'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'group'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'userapp'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'plugin'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'custom'</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//广告类型适用的投放范围</span>
    <span class="token keyword">var</span> <span class="token variable">$imagesizes</span> <span class="token operator">=</span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token string single-quoted-string">'120x60'</span><span class="token punctuation">,</span> <span class="token string single-quoted-string">'120x240'</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//图片广告推荐大小</span>
    <span class="token keyword">function</span> <span class="token function-definition function">getsetting</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//返回设置项目</span>
        <span class="token variable">$settings</span> <span class="token operator">=</span> <span class="token keyword">array</span><span class="token punctuation">(</span>
            <span class="token string single-quoted-string">'text'</span> <span class="token operator">=></span> <span class="token keyword">array</span><span class="token punctuation">(</span>
                <span class="token string single-quoted-string">'title'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'text_title'</span><span class="token punctuation">,</span><span class="token comment">//设置项目名称 (可填写语言项目)</span>
                <span class="token string single-quoted-string">'type'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'mradio'</span><span class="token punctuation">,</span><span class="token comment">//项目类型</span>
                <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token comment">//项目选项</span>
                <span class="token string single-quoted-string">'default'</span> <span class="token operator">=></span> <span class="token number">0</span><span class="token punctuation">,</span><span class="token comment">//项目默认值</span>
            <span class="token punctuation">)</span>
        <span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token variable">$settings</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">setsetting</span><span class="token punctuation">(</span><span class="token operator">&amp;</span><span class="token variable">$advnew</span><span class="token punctuation">,</span> <span class="token operator">&amp;</span><span class="token variable">$parameters</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//保存设置项目</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">evalcode</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//广告显示时的运行代码</span>
        <span class="token keyword">return</span> <span class="token keyword">array</span><span class="token punctuation">(</span>
            <span class="token comment">//检测广告是否投放时的代码</span>
            <span class="token string single-quoted-string">'check'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'
            if(condition) {
                $checked = false;
            }'</span><span class="token punctuation">,</span>
            <span class="token comment">//广告显示时的代码 (随机调用投放的广告)</span>
            <span class="token string single-quoted-string">'create'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'$adcode = $codes[$adids[array_rand($adids)]];'</span><span class="token punctuation">,</span>
        <span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token delimiter important">?></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="道具类" tabindex="-1"><a class="header-anchor" href="#道具类"><span>道具类</span></a></h2>
<p>脚本位置：source/class/magic/magic_name.php<br>
语言包位置：source/language/magic/lang_name.php</p>
<h6 id="【discuz-x3-0-新增】-1" tabindex="-1"><a class="header-anchor" href="#【discuz-x3-0-新增】-1"><span>【Discuz! X3.0 新增】</span></a></h6>
<p>脚本位置：source/plugin/插件目录/magic/magic_name.php<br>
图标：source/plugin/插件目录/magic/magic_name.small.gif、source/plugin/插件目录/magic/magic_name.gif</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token php language-php"><span class="token delimiter important">&lt;?php</span>
<span class="token keyword">class</span> <span class="token class-name-definition class-name">magic_name</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> <span class="token variable">$version</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'1.0'</span><span class="token punctuation">;</span><span class="token comment">//脚本版本号</span>
    <span class="token keyword">var</span> <span class="token variable">$name</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'name'</span><span class="token punctuation">;</span><span class="token comment">//道具名称 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$description</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'desc'</span><span class="token punctuation">;</span><span class="token comment">//道具说明 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$price</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'10'</span><span class="token punctuation">;</span><span class="token comment">//道具默认价格</span>
    <span class="token keyword">var</span> <span class="token variable">$weight</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'10'</span><span class="token punctuation">;</span><span class="token comment">//道具默认重量</span>
    <span class="token keyword">var</span> <span class="token variable">$copyright</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'Comsenz Inc.'</span><span class="token punctuation">;</span><span class="token comment">//版权 (可填写语言包项目)</span>
    <span class="token keyword">function</span> <span class="token function-definition function">getsetting</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//返回设置项目</span>
        <span class="token variable">$settings</span> <span class="token operator">=</span> <span class="token keyword">array</span><span class="token punctuation">(</span>
            <span class="token string single-quoted-string">'text'</span> <span class="token operator">=></span> <span class="token keyword">array</span><span class="token punctuation">(</span>
                <span class="token string single-quoted-string">'title'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'text_title'</span><span class="token punctuation">,</span><span class="token comment">//设置项目名称 (可填写语言项目)</span>
                <span class="token string single-quoted-string">'type'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'mradio'</span><span class="token punctuation">,</span><span class="token comment">//项目类型</span>
                <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token comment">//项目选项</span>
                <span class="token string single-quoted-string">'default'</span> <span class="token operator">=></span> <span class="token number">0</span><span class="token punctuation">,</span><span class="token comment">//项目默认值</span>
            <span class="token punctuation">)</span>
        <span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token keyword">return</span> <span class="token variable">$settings</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">setsetting</span><span class="token punctuation">(</span><span class="token operator">&amp;</span><span class="token variable">$advnew</span><span class="token punctuation">,</span> <span class="token operator">&amp;</span><span class="token variable">$parameters</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//保存设置项目</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">usesubmit</span><span class="token punctuation">(</span><span class="token variable">$magic</span><span class="token punctuation">,</span> <span class="token variable">$parameters</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//道具使用</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">show</span><span class="token punctuation">(</span><span class="token variable">$magic</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//道具显示</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token delimiter important">?></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="任务类" tabindex="-1"><a class="header-anchor" href="#任务类"><span>任务类</span></a></h2>
<p>脚本位置：source/class/task/task_name.php<br>
语言包位置：source/language/task/lang_name.php</p>
<h6 id="【discuz-x3-0-新增】-2" tabindex="-1"><a class="header-anchor" href="#【discuz-x3-0-新增】-2"><span>【Discuz! X3.0 新增】</span></a></h6>
<p>脚本位置：source/plugin/插件目录/task/task_name.php<br>
图标：source/plugin/插件目录/task/task_name.gif</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token php language-php"><span class="token delimiter important">&lt;?php</span>
<span class="token keyword">class</span> <span class="token class-name-definition class-name">task_name</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> <span class="token variable">$version</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'1.0'</span><span class="token punctuation">;</span><span class="token comment">//脚本版本号</span>
    <span class="token keyword">var</span> <span class="token variable">$name</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'name'</span><span class="token punctuation">;</span><span class="token comment">//任务名称 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$description</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'desc'</span><span class="token punctuation">;</span><span class="token comment">//任务说明 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$copyright</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'Comsenz Inc.'</span><span class="token punctuation">;</span><span class="token comment">//版权 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$icon</span> <span class="token operator">=</span> <span class="token string single-quoted-string">''</span><span class="token punctuation">;</span><span class="token comment">//默认图标</span>
    <span class="token keyword">var</span> <span class="token variable">$period</span> <span class="token operator">=</span> <span class="token string single-quoted-string">''</span><span class="token punctuation">;</span><span class="token comment">//默认任务间隔周期</span>
    <span class="token keyword">var</span> <span class="token variable">$periodtype</span> <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span><span class="token comment">//默认任务间隔周期单位</span>
    <span class="token keyword">var</span> <span class="token variable">$conditions</span> <span class="token operator">=</span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token comment">//任务附加条件</span>
        <span class="token string single-quoted-string">'text'</span> <span class="token operator">=></span> <span class="token keyword">array</span><span class="token punctuation">(</span>
            <span class="token string single-quoted-string">'title'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'text_title'</span><span class="token punctuation">,</span><span class="token comment">//设置项目名称 (可填写语言项目)</span>
            <span class="token string single-quoted-string">'type'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'mradio'</span><span class="token punctuation">,</span><span class="token comment">//项目类型</span>
            <span class="token string single-quoted-string">'value'</span> <span class="token operator">=></span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span><span class="token comment">//项目选项</span>
            <span class="token string single-quoted-string">'default'</span> <span class="token operator">=></span> <span class="token number">0</span><span class="token punctuation">,</span><span class="token comment">//项目默认值</span>
            <span class="token string single-quoted-string">'sort'</span> <span class="token operator">=></span> <span class="token string single-quoted-string">'complete'</span><span class="token punctuation">,</span><span class="token comment">//条件类型 (apply:申请任务条件 complete:完成任务条件)</span>
        <span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token keyword">function</span> <span class="token function-definition function">preprocess</span><span class="token punctuation">(</span><span class="token variable">$task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//申请任务成功后的附加处理</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">csc</span><span class="token punctuation">(</span><span class="token variable">$task</span> <span class="token operator">=</span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//判断任务是否完成 (返回 TRUE:成功 FALSE:失败 0:任务进行中进度未知或尚未开始  大于0的正数:任务进行中返回任务进度)</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">sufprocess</span><span class="token punctuation">(</span><span class="token variable">$task</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//完成任务后的附加处理</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">view</span><span class="token punctuation">(</span><span class="token variable">$task</span><span class="token punctuation">,</span> <span class="token variable">$taskvars</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//任务显示</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">install</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//任务安装的附加处理</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">uninstall</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//任务卸载的附加处理</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">upgrade</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//任务升级的附加处理</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token delimiter important">?></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="验证问答类" tabindex="-1"><a class="header-anchor" href="#验证问答类"><span>验证问答类</span></a></h2>
<p>脚本位置：source/class/secqaa/secqaa_name.php<br>
语言包位置：source/language/secqaa/lang_name.php</p>
<h6 id="【discuz-x3-0-新增】-3" tabindex="-1"><a class="header-anchor" href="#【discuz-x3-0-新增】-3"><span>【Discuz! X3.0 新增】</span></a></h6>
<p>脚本位置：source/plugin/插件目录/secqaa/secqaa_name.php</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token php language-php"><span class="token delimiter important">&lt;?php</span>
<span class="token keyword">class</span> <span class="token class-name-definition class-name">secqaa_name</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> <span class="token variable">$version</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'1.0'</span><span class="token punctuation">;</span><span class="token comment">//脚本版本号</span>
    <span class="token keyword">var</span> <span class="token variable">$name</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'name'</span><span class="token punctuation">;</span><span class="token comment">//验证问答名称 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$description</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'desc'</span><span class="token punctuation">;</span><span class="token comment">//验证问答说明 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$copyright</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'Comsenz Inc.'</span><span class="token punctuation">;</span><span class="token comment">//版权 (可填写语言包项目)</span>
    <span class="token keyword">function</span> <span class="token function-definition function">make</span><span class="token punctuation">(</span><span class="token operator">&amp;</span><span class="token variable">$question</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//返回安全问答的答案和问题 ($question 为问题，函数返回值为答案)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token delimiter important">?></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="验证码类" tabindex="-1"><a class="header-anchor" href="#验证码类"><span>验证码类</span></a></h2>
<h6 id="【discuz-x2-5-新增】" tabindex="-1"><a class="header-anchor" href="#【discuz-x2-5-新增】"><span>【Discuz! X2.5 新增】</span></a></h6>
<p>脚本位置：source/class/seccode/seccode_name.php<br>
语言包位置：source/language/seccode/lang_name.php</p>
<h6 id="【discuz-x3-0-新增】-4" tabindex="-1"><a class="header-anchor" href="#【discuz-x3-0-新增】-4"><span>【Discuz! X3.0 新增】</span></a></h6>
<p>脚本位置：source/plugin/插件目录/seccode/seccode_name.php</p>
<div class="language-php line-numbers-mode" data-ext="php" data-title="php"><pre v-pre class="language-php"><code><span class="token php language-php"><span class="token delimiter important">&lt;?php</span>
<span class="token keyword">class</span> <span class="token class-name-definition class-name">seccode_name</span> <span class="token punctuation">{</span>
    <span class="token keyword">var</span> <span class="token variable">$version</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'1.0'</span><span class="token punctuation">;</span><span class="token comment">//脚本版本号</span>
    <span class="token keyword">var</span> <span class="token variable">$name</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'name'</span><span class="token punctuation">;</span><span class="token comment">//验证码类型名称 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$copyright</span> <span class="token operator">=</span> <span class="token string single-quoted-string">'Comsenz Inc.'</span><span class="token punctuation">;</span><span class="token comment">//版权 (可填写语言包项目)</span>
    <span class="token keyword">var</span> <span class="token variable">$setting</span> <span class="token operator">=</span> <span class="token keyword">array</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//后台设置后的变量</span>
    <span class="token keyword">function</span> <span class="token function-definition function">check</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//检查输入的验证码，返回 true 表示通过        </span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">make</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//输出验证码，echo 输出内容将显示在页面中</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">function</span> <span class="token function-definition function">image</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token punctuation">{</span><span class="token comment">//纯图片验证码 URL，用于移动端显示(Discuz! X3.1 新增)</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
<span class="token delimiter important">?></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


